### ISSUE TITLE
how to change the position of month labels to below heatmap?

### ISSUE THREAD

**Issue by ajmalp5** [uiwjs/react-heat-map#114]

**Comment by jaywcjlove** [comment]
How to change position?
@ajmalp5

**Comment by ajmalp5** [comment]
In default, Month labels are shown above the Heatmap. How can I customize the month labels and how I can show month labels below Heatmap?

**Comment by jaywcjlove** [comment]
```diff
<HeatMap
+  monthPlacement="bottom"
  />
```

Upgrade `v2.2.0`
