### ISSUE TITLE
when I clicking on any of react in svg it is changing its color to green but i want red how can i do that? and how this panel color are working ?

### ISSUE THREAD

**Issue by pradeep800** [uiwjs/react-heat-map#121]

**Comment by jaywcjlove** [comment]
https://github.com/uiwjs/react-heat-map/blob/718146d0d5407aab564b8403995d697aeb67ece9/core/src/style/index.less#L15-L18

@pradeep800 You can write styles to set it.

**Comment by jaywcjlove** [comment]
@pradeep800 

1. Updating to **`v2.1.0`** can change this via css variables. Example: https://codesandbox.io/embed/https-github-com-uiwjs-react-heat-map-issues-121-example-02-t8gzzn?fontsize=14&hidenavigation=1&theme=dark

```diff
<HeatMap
  value={value}
  width={600}
  style={{
    "--rhm-rect": "#b9b9b9",
+    "--rhm-rect-active": "red"
  }}
```

2. Can be overridden by styles before updating to **`v2.0.5`**. Example: https://codesandbox.io/embed/https-github-com-uiwjs-react-heat-map-issues-121-example-01-zr2p5p?fontsize=14&hidenavigation=1&theme=dark

```css
svg.w-heatmap rect:active {
  fill: red;
}
```

**Comment by pradeep800** [comment]
thank you for answering it is working correctly but I am getting error in production can you please help me that?
error photo: - https://drive.google.com/file/d/1WIkE-lTfc8rZcw3edFdm6s56TKv-ST8m/view?usp=sharing
code:- https://github.com/pradeep800/striver-sheet-webiste/blob/main/components/mainProfile.tsx#L84-L103 @jaywcjlove

**Comment by pradeep800** [comment]
i am using next js 13*

**Comment by jaywcjlove** [comment]
@pradeep800 Upgrade `v2.1.1`

```diff
    rectRender={(props, data) => {
      // if (!data.count) return <rect {...props} />;
      return (
-        <Tooltip key={props.key} placement="top" content={`count: ${data.count || 0}`}>
+        <Tooltip placement="top" content={`count: ${data.count || 0}`}>
          <rect {...props} />
        </Tooltip>
      );
    }}
```

**Comment by pradeep800** [comment]
> thank you for answering it is working correctly but I am getting error in production can you please help me that? error photo: - https://drive.google.com/file/d/1WIkE-lTfc8rZcw3edFdm6s56TKv-ST8m/view?usp=sharing code:- https://github.com/pradeep800/striver-sheet-webiste/blob/main/components/mainProfile.tsx#L84-L103 @jaywcjlove

still same error ?

**Comment by pradeep800** [comment]
btw you can see code btw there is no error in production

**Comment by jaywcjlove** [comment]
<img width="1391" alt="image" src="https://github.com/uiwjs/react-heat-map/assets/1680273/95638021-9fca-42ff-8cf1-22036d9e5fe7">

@pradeep800 Oh my example works fine.

**Comment by pradeep800** [comment]
use tooltip then it's giving error

**Comment by jaywcjlove** [comment]
https://codesandbox.io/embed/sweet-aj-jpl6mx?fontsize=14&hidenavigation=1&theme=dark

```jsx
import Tooltip from "@uiw/react-tooltip";
import HeatMap from "@uiw/react-heat-map";

const value = [
  { date: "2016/01/11", count: 2 },
  ...[...Array(17)].map((_, idx) => ({
    date: `2016/01/${idx + 10}`,
    count: idx
  })),
  ...[...Array(17)].map((_, idx) => ({
    date: `2016/02/${idx + 10}`,
    count: idx
  })),
  { date: "2016/04/12", count: 2 },
  { date: "2016/05/01", count: 5 },
  { date: "2016/05/02", count: 5 },
  { date: "2016/05/03", count: 1 },
  { date: "2016/05/04", count: 11 },
  { date: "2016/05/08", count: 32 }
];

export default function App() {
  return (
    <div>
      <HeatMap
        value={value}
        width={600}
        startDate={new Date("2016/01/01")}
        rectRender={(props, data) => {
          console.log("props", props);
          // if (!data.count) return <rect {...props} />;
          return (
            <Tooltip placement="top" content={`count: ${data.count || 0}`}>
              <rect {...props} />
            </Tooltip>
          );
        }}
      />
    </div>
  );
}

```
