### ISSUE TITLE
app-index.js:35 Warning: A props object containing a "key" prop is being spread into JSX:   let props = {key: someKey, rx: ..., fill: ..., width: ..., height: ..., x: ..., y: ..., render: ..., value: ..., data-date: ..., data-index: ..., data-row: ..., data-column: ...};   <Rect {...props} /> React keys must be passed directly to JSX without using spread:   let props = {rx: ..., fill: ..., width: ..., height: ..., x: ..., y: ..., render: ..., value: ..., data-date: ..., data-index: ..., data-row: ..., data-column: ...};   <Rect key={someKey} {...props} />

### ISSUE THREAD

**Issue by ruru-m07** [uiwjs/react-heat-map#128]
app-index.js:35 Warning: A props object containing a "key" prop is being spread into JSX:
  let props = {key: someKey, rx: ..., fill: ..., width: ..., height: ..., x: ..., y: ..., render: ..., value: ..., data-date: ..., data-index: ..., data-row: ..., data-column: ...};
  <Rect {...props} />
React keys must be passed directly to JSX without using spread:
  let props = {rx: ..., fill: ..., width: ..., height: ..., x: ..., y: ..., render: ..., value: ..., data-date: ..., data-index: ..., data-row: ..., data-column: ...};
  <Rect key={someKey} {...props} />
  
  
  
![image](https://github.com/uiwjs/react-heat-map/assets/142723369/e06812b5-112a-41cb-84b2-4d4e7b97c59c)

```javascript
<HeatMap
              value={value}
              width={700}
              style={{
                color: "#fafafa",
              }}
              legendCellSize={0}
              rectSize={10}
              startDate={
                new Date(new Date().setDate(new Date().getDate() - 365))
              }
              endDate={new Date()}
              monthLabels={[
                "Jan",
                "Feb",
                "Mar",
                "Apr",
                "May",
                "Jun",
                "Jul",
                "Aug",
                "Sep",
                "Oct",
                "Nov",
                "Dec",
              ]}
              weekLabels={["", "Mon", "", "Wed", "", "Fri", ""]}
              panelColors={{
                0: "#202020",
                2: "#525252",
                4: "#71717a",
                10: "#a3a3a3",
                20: "#d4d4d4",
                30: "#e5e5e5",
              }}
              rectProps={{
                rx: 2.5,
              }}
            />
```

![image](https://github.com/uiwjs/react-heat-map/assets/142723369/5cf71e22-5edf-4b80-9478-db0f7f5f1174)

![image](https://github.com/uiwjs/react-heat-map/assets/142723369/ee6489e7-5ed8-4ce7-a1fd-0f415c5efae0)

![image](https://github.com/uiwjs/react-heat-map/assets/142723369/5917cb69-6bcc-4b56-8a32-d142d844be22)

```  "@uiw/react-heat-map": "^2.2.1", ```

nextjs 14.

need help

**Comment by jaywcjlove** [comment]
@ruru-m07 If you can provide an example of a reproducible error, I'll take a look.

**Comment by ruru-m07** [comment]
@jaywcjlove  i have not more info! but i also provide u all info what u need more???

**Comment by jaywcjlove** [comment]
@ruru-m07 Provide examples of reproducible errors

**Comment by greengem** [comment]
Happening to me too. with a default next 14 project and using the lib in a file marked 'use client'

Warning: A props object containing a "key" prop is being spread into JSX:


I'll try to get a reproducible project up over the weekend

**Comment by greengem** [comment]
@jaywcjlove 
https://github.com/greengem/react-heat-map-issue
I kept the project as simple as possible

**Comment by greengem** [comment]
> @greengem thx! I fixed. upgrade `v2.2.2`

thanks. working great for me now
