### ISSUE TITLE
RangeError: Invalid array length

### ISSUE THREAD

**Issue by excxapp** [uiwjs/react-heat-map#24]
<g transform={`translate(${leftPad}, ${topPad})`}>

错误提示这一行，请问是什么问题

**Comment by jaywcjlove** [comment]
@excxapp 有实例？

**Comment by excxapp** [comment]
![image](https://user-images.githubusercontent.com/4355581/129300615-bc751419-66a9-457a-939e-e10d74e4d1b6.png)
我的场景是，列表也，会多次重新渲染，popover上的。
方便给个微信啥的不

**Comment by jaywcjlove** [comment]
@excxapp 提供一个实例我看看。

**Comment by excxapp** [comment]
我项目里面用的用的，没有拆解的出来。
具体就是，我reacthook里面
会重新渲染 value

**Comment by excxapp** [comment]
![image](https://user-images.githubusercontent.com/4355581/129301203-e04e9b92-db0d-4b56-bfd2-f4fb3711b4f1.png)
![image](https://user-images.githubusercontent.com/4355581/129301227-6d2155e5-a2f4-4b63-9588-c0b8592be18e.png)
这是用到的两部分

**Comment by jaywcjlove** [comment]
@excxapp 你抽出来放到一个  repo 中，我方便测试，截图我怎么调试呢？

**Comment by jaywcjlove** [comment]
@excxapp 你使用的 `Tooltip` 有没有破坏 svg ？

**Comment by excxapp** [comment]
tooltip是ant的，不是你们那个，因为你们那个层级太低。我注视掉tooltips一样抱错。

**Comment by jaywcjlove** [comment]
@excxapp 我不太知道你什么原因，没有示例，没有办法解决

**Comment by excxapp** [comment]
你一个页面多次渲染一个通过按钮点击改变value，value每次都一样的情况，你测试下应该就能重现了

**Comment by jaywcjlove** [comment]
@excxapp 我看了官网示例，没有问题，如果你没有提供示例，我没有办法解决你的问题。

**Comment by jaywcjlove** [comment]
@excxapp 你可以通过 `npx create-kkt my-app` 创建一个简单的工程，重现你的bug，然后我帮你调试一下

**Comment by excxapp** [comment]
我自己修改了源码加了判断是可以了

**Comment by jaywcjlove** [comment]
@excxapp 好吧，欢迎提交 PR

**Comment by excxapp** [comment]
> @excxapp 好吧，欢迎提交 PR

好的，我系统babel没升级，所以我没跑你这个项目。我改了2个地方
LablesMonth.tsx  line-22
`
if (monthLables === false) return [];
改为
if (monthLables === false || colNum<1) return [];
`
SVG.tsx line 104

`
 {gridNum&&gridNum >0&&[...Array(gridNum)].map((_, idx) => {
`

**Comment by jaywcjlove** [comment]
@excxapp Upgrade `@uiw/react-heat-map@1.3.4`
