### ISSUE TITLE
next 安装不了，next 不支持全局导入 css

### ISSUE THREAD

**Issue by JeffreyBool** [uiwjs/react-heat-map#33]

**Comment by jaywcjlove** [comment]
@JeffreyBool 参考方法：https://github.com/uiwjs/react-md-editor/issues/52#issuecomment-848969341

**Comment by jaywcjlove** [comment]
使用 [next-remove-imports](https://github.com/uiwjs/next-remove-imports) 删除包内部导入的 css，在 nextjs 项目中引入 css

```jsx
import '@uiw/react-heat-map/dist.css';
```

**Comment by JeffreyBool** [comment]
![image](https://user-images.githubusercontent.com/24415888/132555880-ea4bfd1f-96f4-4a45-a11c-72d9da19cc6d.png)


![image](https://user-images.githubusercontent.com/24415888/132555905-8d7c00e5-eff6-4379-93f2-abecd2dc555f.png)
 咋没图表数据呢

**Comment by jaywcjlove** [comment]
@JeffreyBool  Upgrade `@uiw/react-heat-map@v1.4.1`
