### ISSUE TITLE
website example cannot accessed

### ISSUE THREAD

**Issue by esafata** [uiwjs/react-heat-map#43]
uiwjs.github.io/react-heat-map/
this website cannot accessed.
So i cannot try it the project

**Comment by jaywcjlove** [comment]
@esafata I guess you are in China.

**Comment by esafata** [comment]
nope. How to i can try it?

**Comment by jaywcjlove** [comment]
@esafata https://www.astrill.com

**Comment by jaywcjlove** [comment]
![image](https://user-images.githubusercontent.com/1680273/133021660-2b099de8-3f8d-49ce-96ed-482d7e738835.png)

**Comment by esafata** [comment]
what is this code can integratted with my NextJS project?

**Comment by jaywcjlove** [comment]
https://github.com/uiwjs/react-md-editor/issues/52#issuecomment-848969341
@esafata

**Comment by esafata** [comment]
import ReactDOM from 'react-dom';
import HeatMap from '@uiw/react-heat-map';

const value = [
  { date: '2016/01/11', count: 2 },
  { date: '2016/01/12', count: 20 },
  { date: '2016/01/13', count: 10 },
  ...[...Array(17)].map((_, idx) => ({ date: `2016/02/${idx + 10}`, count: idx, content: '' })),
  { date: '2016/04/11', count: 2 },
  { date: '2016/05/01', count: 5 },
  { date: '2016/05/02', count: 5 },
  { date: '2016/05/04', count: 11 },
];

const Demo = () => {
  return (
    <div>
      <HeatMap value={value} startDate={new Date('2016/01/01')} />
    </div>
  )
};
ReactDOM.render(<Demo />, _mount_);



this code is in a new file created or there is on the repository file?

**Comment by jaywcjlove** [comment]
@esafata You are asking how the sample code is displayed?

**Comment by esafata** [comment]
where the sample code existed? 

i dont know how to start use the code

**Comment by jaywcjlove** [comment]
@esafata The sample code is in REAME.md

**Comment by jaywcjlove** [comment]
Example: https://github.com/uiwjs/react-heat-map/blame/main/README.md#L26-L50

**Comment by jaywcjlove** [comment]
```markdown
<!--rehype:bgWhite=true&codeSandbox=true&codePen=true-->
```jsx
\```
```

https://github.com/uiwjs/react-heat-map/blob/bfbac6f6ef0a870f67fc0cd23fd3c25b81054d57/website/App.tsx#L38

**Comment by esafata** [comment]
I mean, where i write the sample code? on the new file or on the file existed?

**Comment by esafata** [comment]
on my project there is not file with extention .tsx

only .js in my project

**Comment by jaywcjlove** [comment]
@esafata https://codesandbox.io/s/react-heat-map-example-forked-k8knw?file=/src/index.js

**Comment by esafata** [comment]
Thanks, i got it. 👍 👍

**Comment by esafata** [comment]
![image](https://user-images.githubusercontent.com/49476864/133152800-06546bd2-43ff-43fd-b861-412d9557f583.png)

have worked 👍
